export const ADD_CHARACTER_TO_FAVORITES = 'ADD_CHARACTER_TO_FAVORITES';
export const REMOVE_CHARACTER_FROM_FAVORITES = 'REMOVE_CHARACTER_FROM_FAVORITES';
export const FILTER= 'FILTER';
export const ORDER = 'ORDER';